# Generated by Django 5.0.6 on 2024-06-09 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=300, verbose_name='Улица')),
                ('building', models.CharField(max_length=100, verbose_name='Дом')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600, verbose_name='Название')),
                ('model', models.CharField(max_length=600, verbose_name='Модель')),
                ('date', models.DateField(verbose_name='Дата производства')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyChainParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('debt', models.IntegerField(verbose_name='Задолженность')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_factory', models.BooleanField(default=False, verbose_name='Это завод')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.contact', verbose_name='Контакты')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.product', verbose_name='Продукт')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.supplychainparticipant', verbose_name='Поставщик')),
            ],
        ),
    ]
