# Generated by Django 5.0.6 on 2024-06-11 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_remove_supplychainparticipant_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplychainparticipant',
            options={},
        ),
        migrations.RemoveField(
            model_name='supplychainparticipant',
            name='is_factory',
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=300, verbose_name='Улица')),
                ('building', models.CharField(max_length=100, verbose_name='Дом')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Завод-производитель',
                'verbose_name_plural': 'Заводы-производители',
            },
        ),
    ]
