# Generated by Django 5.0.6 on 2024-06-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_supplychainparticipant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplychainparticipant',
            options={'verbose_name': 'Участник цепи поставок', 'verbose_name_plural': 'Участники цепи поставок'},
        ),
        migrations.AddField(
            model_name='supplychainparticipant',
            name='is_factory',
            field=models.BooleanField(default=False, verbose_name='Это завод'),
        ),
        migrations.DeleteModel(
            name='Factory',
        ),
    ]
